##################################
##    Fichero de propiedades    ##
##################################

# Nombre común de los archivo de entrada, es decir de los archivos de salida del Sistema
input_name: output

# Direccion URL a la que se ha de buscar los csv
# IMPORTANTE: Debe terminar con una barra (\ o /)
input_base_url: [ejecuciones/analisis parametrico/SVNS/alphas.parte2/]

# path RELATIVO a *input_base_url* donde almacenar las gráficas de salida
# IMPORTANTE: Debe terminar con una barra (\ o /) y comenzar sin ella
output_path: graficas/

# nombre de la grafica de salida
fig_name: grafica_alphas_2


# --

# posibles valores: 'iteracion', 'tiempo (ms)', 'fitness mejor', 'tamaño', 'numIterSinMejora',
#  'vecindad', 'fitness sol actual', 'fitness BL', 'distancia'
column_to_plot: "fitness mejor"

# identificador de ejecucion inicial
start_id: 1


## nombres de la leyenda de la gráfica
## representa el significado de cada fichero:

# string a anteponer al valor de cada ejecución en la leyenda de la gráfica
parametro: "\u03B1 = "

# lista de valores de cada ejecucion ordenada por id de la misma
valores: [15, 15.5, 16, 16.5, 17, 17.5, 18, 18.5, 19, 19.5, 20]


# --


# etiqueta para el eje Y
name_y_axis: Fitness

fig_title: "Fitness e iteraciones SVNS por 10 minutos usando diferentes valores de \u03B1"

## Decide si mostrar o no el Slider dinamico.
# Solo disponible en el formato de salida HTML
show_slider: true

