##############################################
##    Fichero de propiedades por defecto    ##
##############################################

# Nombre común de los archivo de entrada, es decir de los archivos de salida del Sistema
input_name: output

# Direccion URL a la que se ha de buscar los csv
# IMPORTANTE: Debe terminar con una barra (\ o /)
input_base_url: [ ejecuciones/entornos probabilisticos/2_6-11-2019/Caso1Id1m-01-01-2019/VNS/Trazas/,
                  ejecuciones/entornos probabilisticos/2_6-11-2019/Caso3Id2m-01-01-2019/VNS/Trazas/,
                  ejecuciones/entornos probabilisticos/2_6-11-2019/Caso4Id3t-16-01-2019/VNS/Trazas/,
                  ejecuciones/entornos probabilisticos/2_6-11-2019/Caso5Id5t-16-01-2019/VNS/Trazas/,
                  ejecuciones/entornos probabilisticos/2_6-11-2019/Caso6Id4t-14-01-2019/VNS/Trazas/,
                  ejecuciones/entornos probabilisticos/2_6-11-2019/Caso7Id6t-19-10-2018/VNS/Trazas/,
                  ejecuciones/entornos probabilisticos/2_6-11-2019/Caso8Id0m-13-09-2018/VNS/Trazas/,
                  ejecuciones/entornos probabilisticos/2_6-11-2019/Caso9Id1m-13-09-2018/VNS/Trazas/ ]

# path RELATIVO a *input_base_url* donde almacenar las gráficas de salida
# IMPORTANTE: Debe terminar con una barra (\ o /) y comenzar sin ella
output_path: ../Graficas/tiempo/

# nombre del fichero de salida
fig_name: grafica_fitness_entornos_probabilisticos_tiempo


# -- DATA:

# nombres de las columnas de los ficheros
# no tienen por que corresponderse con las cabeceras
# la columna 'iteracion' es obligatoria y debe aparecer con ese nombre
column_names: ['iteracion', 'tiempo', 'fitness mejor',
               'fitness 1', 'fitness 2', 'fitness 3', 'fitness 4',
               'tamaño', 'porcentaje mejora', 'vecindad',
               "mejor fitness", "distancia"
]

# posibles valores: ver "column_names"
x_axis_variable: "tiempo"
y_axis_variable: "fitness mejor"

# identificador de ejecucion inicial
start_id: 1


## nombres de la leyenda de la gráfica
## representa el significado de cada fichero:

# string a anteponer al valor de cada ejecución en la leyenda de la gráfica
parametro: ""

# lista de valores de cada ejecucion ordenada por id de la misma
valores: [VND, RVNS, BVNS, GVNS, SVNS]


# -- APPEARANCE:


# etiqueta para el eje Y
name_y_axis: Fitness

fig_title: "Ejecución por 10 minutos con entornos probabilísticos"
fig_subtitles: [Caso 1,Caso 3,Caso 4,Caso 5,Caso 6,Caso 7,Caso 8,Caso 9]

## Decide si mostrar o no el Slider dinamico.
# Solo disponible en el formato de salida HTML
show_slider: true

